//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPE
    {
        public int ID { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Site_ID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CPECategory_ID { get; set; }
        public string SIMNo { get; set; }
        public Nullable<int> ToSite { get; set; }
        public string CodeTransfer { get; set; }
        public Nullable<int> FromSite { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
    }
}
