//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContextCPEDB : DbContext
    {
        public DBContextCPEDB()
            : base("name=DBContextCPEDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agent> Agents { get; set; }
        public DbSet<CPE> CPEs { get; set; }
        public DbSet<CPEGlobal> CPEGlobals { get; set; }
        public DbSet<CPELocation> CPELocations { get; set; }
        public DbSet<LoanDetail> LoanDetails { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Package> Packages { get; set; }
        public DbSet<Penalty> Penalties { get; set; }
        public DbSet<Promotion> Promotions { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<TrackLoan> TrackLoans { get; set; }
        public DbSet<TrackLog> TrackLogs { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Loan> Loans { get; set; }
    }
}
