//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetail
    {
        public int ID { get; set; }
        public Nullable<int> Loan_ID { get; set; }
        public Nullable<int> RentDay { get; set; }
        public Nullable<float> PenaltyAmount { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<float> RentAmount { get; set; }
        public Nullable<float> Deposit { get; set; }
        public Nullable<int> SiteLoan_ID { get; set; }
        public Nullable<int> SiteReturn_ID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> CPE_ID { get; set; }
        public Nullable<int> PromotionDisCount { get; set; }
        public string AgentCode { get; set; }
    
        public virtual Loan Loan { get; set; }
    }
}
