//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public Loan()
        {
            this.LoanDetails = new HashSet<LoanDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Staff_ID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerBarcode { get; set; }
        public string ReturnType { get; set; }
        public Nullable<int> LoanSiteID { get; set; }
        public Nullable<float> Delivery { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<float> RentalPrice { get; set; }
        public Nullable<float> OnlineDiscount { get; set; }
        public string OnlineDiscountCode { get; set; }
        public Nullable<float> SubTotal { get; set; }
        public string CreditCardNumer { get; set; }
        public Nullable<System.DateTime> ExpiredateCreditCard { get; set; }
        public string NameOnCard { get; set; }
        public string BookedName { get; set; }
    
        public virtual ICollection<LoanDetail> LoanDetails { get; set; }
    }
}
