//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<float> Amount { get; set; }
        public Nullable<int> Percents { get; set; }
        public Nullable<int> StatusCPE { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> Modified_By { get; set; }
    }
}
