//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public Nullable<byte> Sex { get; set; }
        public string Phone { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<int> Site_ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public string HomePhone { get; set; }
    }
}
